mongo:
  image: mongo:3.2.0
  command: mongod --smallfiles
  ports:
    - 27017
  volumes:
    - /data/api-mongodb-template/mongo:/data/db

local:
  build: .
  ports:
    - 3000
  volumes:
    - .:/src
  links:
    - mongo
  environment:
    NODE_ENV: development
